### ISSUE TITLE
Custom type mappings

### ISSUE THREAD

**Issue by bjyoungblood** [vattle/sqlboiler#100]
My main project is an application that uses a lot of financial data. We store all of our financial data in our database as `decimal` fields (as a side note, this type is currently unmapped in the MySQL driver, so our decimals end up as strings -- but this actually turns out to be better than floats).

Ultimately, what we need is to be able to tell SQLBoiler to use an an arbitrary-precision type for any floating-point value (float / double / real / decimal / numeric). This was [very easy to achieve](https://github.com/bjyoungblood/sqlboiler/commit/2100d49196d69c14c4ff76defeec72904351b4e4) by changing a few lines.

One way to control this would be to add a `--float-type` flag (similar to the existing `tinyint-as-bool` option). However, I thought it would be worth discussing whether it would make sense (or even be possible) to give the user a way to override any type mapping.

A few things I'm not quite sure about yet:

- How to define mappings. Based on `DbType` or `FullDbType` -- both seem like they would have limitations (I'm thinking it would be nice to implement `tinyint-as-bool` this way)
- How to deal with Postgres arrays (I haven't had a chance to use SQLBoiler with Postgres yet)
- It could be hard to maintain backwards compatibility, so this might need to be a v3 feature

If this sounds like a feature you'd be interested in, I'd be happy to put together a PR.

**Comment by aarondl** [comment]
This is definitely something we've thought about in the past. It's a complexity trade-off we had written off in favor of mappings that would mostly work for everyone. I wanted to avoid something that would inevitably end up as complicated or more than things like https://github.com/knq/xo#command-line

We actually had a lot of discussion about how to deal with decimal. I'm kinda surprised to see the postgres driver turns them into float64 because as you say - it's basically strictly worse than a string for the use case. That'll have to be a v3 breakage.

One of the challenges with the custom mappings is custom imports as well. As you saw you had to add one to use the decimal library you wanted to do, so it's something to keep in mind. I think the key is to have three different fields that can be used to construct an "and" condition that would check DBType, FullDBType, and the PG-specific (arrays) ArrType.

Another problem is that the tests we generate use a randomization function that knows all the types in use and how to deal with them. I'm not sure that this is something we can overcome without a complete redo of that system, and even then I'm not sure what that system would have to become to make it work.

One more downside is we unfortunately can't use the same toml configuration file since that one is specifically NOT meant to be in source control and this one would have to be. It might be worth it to consider an options file and a secrets file since I realize that the configuration file as is is partially split anyway, where you need to blacklist things consistently across your team. Assuming we'd do the splitting of config files maybe something like this:

```toml
# normal sqlboiler options here
blacklist = ["sql_migrations"]

[[mappings]]
full_db_type = "ARRAY"
db_type      = "USER-DEFINED"
arr_type     = "int"
import = "github.com/bodetree/decimal"
type   = "decimal.Decimal"
```

I'll end this comment by asking if you think this feature is truly necessary. Do we actually just need a decimal type, or do we need this feature? The tinyint-as-bool was sort of a gross oversight in MySQL land because we didn't know the landscape well (that it had been lacking bool for so long) and maybe it could be viewed as a corner case. Anyway, if the community sees this as the way to go, I can't really push back too much. What do you think? I'll also discuss this with @nullbio.

**Comment by bjyoungblood** [comment]
Ultimately, I don't think it would provide enough benefit when weighed against the complexities. For now, it's far simpler to provide a decimal type and a flag to turn it on/off.

Now that I think about it, a better way to support custom mappings would be to make it possible to use custom drivers (would be a good use of the new plugin build mode). This seems like it would be a far better approach -- if someone truly needs custom mappings, then just exposing it through config probably won't be enough to satisfy their use case.

**Comment by aarondl** [comment]
I think that's a great idea. We considered having "import to load" style plugins like other Go projects (notably `database/sql` itself), but it doesn't really fit here since SQLBoiler is distributed as a binary. If it could dynamically load the modules (in Go 1.8, when we started SQLBoiler Go 1.7 was just out so we didn't have the option then), I think that'd be really awesome. I'd love a PR that looks like that. If not we may get to it eventually. We may also consider moving the drivers to separate repos then to facilitate fork & change, but we'll make that the second iteration.

**Comment by pennersr** [comment]
@aarondl You write:

> We actually had a lot of discussion about how to deal with decimal. I'm kinda surprised to see the postgres driver turns them into float64 because as you say - it's basically strictly worse than a string for the use case. That'll have to be a v3 breakage.

I fully agree with the above. Yet, I currently don't see an open issue v3 dedicated to the above. Should it be opened?

Also, I am wondering if you ever considered simply using `shopspring/decimal` out of the box by default. That would make things way more usable and KISS, compared to using just `string`, or having to plug in custom types for such a standard use case such as decimals.

**Comment by aarondl** [comment]
@pennersr See issue #162
