### ISSUE TITLE
Bulk Insert Operation

### ISSUE THREAD

**Issue by c3mb0** [vattle/sqlboiler#101]
I've looked around the documentation and source code but haven't found a practical way of inserting multiple values into a table. Right now I'm using raw SQL for this purpose. Is such a feature on the way, or would you accept a PR? Let me know if I'm missing something obvious, thanks!

**Comment by aarondl** [comment]
We don't have any way to do bulk insertion and it's not on any roadmaps. Last time I checked at least in Postgres it needed a driver that supported it and weird syntax and queries. It wasn't something we were intending on supporting. I would accept a PR if it was clean enough for both MySQL/Postgres though.

https://godoc.org/github.com/lib/pq#hdr-Bulk_imports

One of the problems with this kind of driver specific code is we don't actually tell people which driver to use at runtime (other than we use drivers that are known good for just retrieving the data we need to generate with). We rely on the interfaces here https://github.com/vattle/sqlboiler/blob/master/boil/db.go#L6 and so I imagine that this sort of thing would complicate the interface to that.

What would you propose?

**Comment by aarondl** [comment]
Stale.

**Comment by ORESoftware** [comment]
bulk insert into postgres at least has a simple api:

```sql
INSERT INTO products (product_no, name, price) VALUES
    (1, 'Cheese', 9.99),
    (2, 'Bread', 1.99),
    (3, 'Milk', 2.99);
```

I assume other relational db engines have very similar syntax, so I don't see why all pg drivers wouldn't support this, seems worth implementing to me.

**Comment by aarondl** [comment]
@ORESoftware bulk insert in postgresql is usually mentioned to be done like so:

https://www.postgresql.org/docs/current/sql-copy.html

**Comment by RichardLindhout** [comment]
Would be great if sqlboiler could support this for now I write custom queries to support this like here but it is a lot of extra work
https://github.com/web-ridge/contact-tracing/blob/main/backend/helpers/convert_batch.go

**Comment by aarondl** [comment]
@RichardLindhout opened to proposals. But it is very difficult since it's not only database specific (mysql vs postgres vs sqlite3 etc) but it's also DRIVER dependent (lib/pq vs pgx etc.)

**Comment by elijahcarrel** [comment]
I've created a snippet for an `Insert` method defined against the auto-generated slice object that I've only tested against MySQL with an InnoDB engine and that I believe will only fully work for MySQL instances with an `innodb_autoinc_lock_mode` of 0 or 1 (for more information on that restriction see https://stackoverflow.com/a/16592867/2736037/). I'm pasting it here: https://gist.github.com/elijahcarrel/b42b0f7437d4646b0b2e6485c4b09ede

If anyone wants to take it the last mile and verify that it works for other database formats, add tests for it, etc. and submit it as a P.R., go ahead! I may find time for that in the future, but might not since I've got it working for my use case, so wanted to just pop this here in case anyone else wants to follow through.
