### ISSUE TITLE
Non selected column should be hidden, or not included

### ISSUE THREAD

**Issue by bxcodec** [vattle/sqlboiler#103]
I don't know if this will possible to do. But I think  it  will be a great feature.
Well, I'm trying  to querying for selecting all data from a table  with specific field

```go
data , err = models.Users(DBCon, qm.Select("id_user", "name","user_photo" ), qm.Where("company_id=?", idCompany)).All()
```

This is the stdout result : 

```go
&{1 Iman {0 false} {photo.png true} {0 false} {0 false} 0 {0001-01-01 00:00:00 +0000 UTC false} {0001-01-01 00:00:00 +0000 UTC false}   <nil> {}}
```

And this is the result  that already encoded to JSON . The unselected column will set to default value, like `nil`, `0` and `""` (empty string)

```json
"data": [
    {
      "id_user": 1,
      "name": "Iman",
      "company_id": null,
      "user_photo": "photo.png",
      "car_id": 0,
      "sex": "",
      "created_at": null,
      "updated_at": null
    }
  ]
```
It will more better, if  it displayed only the selected column.
for example : 

```go
&{1 Iman  {photo.png true} }
```
or in JSON format : 
```json

"data": [
    {
      "id_user": 1,
      "name": "Iman",
      "user_photo": "photo.png"
    }
  ]
```

Well, I didn't expect to much about this. Just hope for the better.

**Comment by aarondl** [comment]
So we already do whatever we can to ensure nullable values are ommitted from the output. I think this is  correct, but I'm happy to think about it some more if valid arguments are made. If the value is not nullable, it should never be able to be null in JSON either. You can see this code here:
https://github.com/vattle/sqlboiler/blob/bfba60eaad30f691f1e3b83882b370223fa5416b/templates/00_struct.tpl#L11

Given that this is already correct there's not too much more we can do since we always return that particular struct. The only thing I can suggest as a workaround is using an anonymous struct to fix it...

```go
data , err = models.Users(DBCon, qm.Select("id_user", "name","user_photo" ), qm.Where("company_id=?", idCompany)).All()

subset := struct{
  IDUser    int    `json:"id_user"`
  Name      string `json:"name"`
  UserPhoto string `json:"user_photo"`
}{data.IDUser, data.Name, data.UserPhoto}

b, err := json.Marshal(subset)
```

Or to use the custom struct to bind immediately to skip the middle man:

```go
subset := struct{
  IDUser    int    `json:"id_user"`
  Name      string `json:"name"`
  UserPhoto string `json:"user_photo"`
}{}

query := models.Users(DBCon,
  qm.Select("id_user", "name","user_photo" ),
  qm.Where("company_id=?", idCompany),
)

err := query.Bind(&subset)
```

Past that, I'm opened to any other ideas on how to accomplish this as I can't think of any :(

**Comment by bxcodec** [comment]
As I said, I'm not expecting to much about this. I think it will be more  "useful" if we can do this. 
Of course , for my current project , I'm using  the custom struct. 
Anyway, thanks for the fast response. Keep improving  :)
