### ISSUE TITLE
created_at nulled on Insert

### ISSUE THREAD

**Issue by jojomi** [vattle/sqlboiler#106]
### What version of SQLBoiler are you using (`sqlboiler --version`)?

SQLBoiler v2.1.4

When I added a `created_at` column, I expected to see that column not touched (by default) when calling `UpdateX` on the model. Instead when the model contained a nil (zero) time struct for `CreatedAt`, the column was changed to `null` in the database.

I see there is a need to be able to change that column's value too, but since it is advertised as auto-managed (and I love that feature!) I would expect it not to be touched unless requested.

Am I missing some way to disable this? The whitelist feature seems a little awkward for achieving this and I did not find any other way without reading data first.

**Comment by aarondl** [comment]
Hey @jojomi, I'm trying to get a crystal clear understanding of what's going on.

1. You had a record in the database, and it had some time value in the `created_at` column from a previous insertion.
2. You called update, and you left the CreatedAt with a zero'd struct.
3. Your record now had a null in the created_at field.

Is this correct? Sorry the wording here is just a bit fuzzy to me so I'm trying to clarify :) If this is the case I'll definitely dig in and fix this, because it shouldn't touch it on Update.

**Comment by jojomi** [comment]
Hey, probably you did a better job figuring out what happened than I did describing it, because it is accurate. If this is unexpected behaviour, I would gladly build a minimal example for debugging.

Initially I rather expected I missed a design decision or some config.

**Comment by aarondl** [comment]
Sorry for the slow response times on this. Will get to this within a day or two. Thanks for the report.

**Comment by aarondl** [comment]
Hey @jojomi, I believe this is fixed now on the dev branch. If you could give it a check that would be great, I want to ensure the behavior matches your expectations now. There was indeed a bug with the Update() method, but unfortunately that behavior for upsert is both desirable and intentional. This comes from the fact that we can't actually tell whether it will update or insert when we do an upsert, so if created_at is missing, we have to fill it in since it might be the insert portion of the upsert. Hopefully that's satisfactory.

**Comment by jojomi** [comment]
Hello @aarondl, thank you very much for having a look at this and tackling it with the said commit. If I understand correctly this bug was independent of the database engine, so postgres was affected as well (just making sure this is in this bug report in case someone ends up here later). I get your point regarding upsert and in my case I am fine adding a `if ... then ... else` condition to do either insert or update.

I will give it a go and report back if it works now as expected.

**Comment by jojomi** [comment]
I did a check using commit a5cb765 (branch `dev`, calls itself `2.1.10`). It worked now as expected, thank you very much, great tool!
