### ISSUE TITLE
Please reduce the number of dependencies to be required in the generated code

### ISSUE THREAD

**Issue by mindreframer** [vattle/sqlboiler#108]
First of all thanks for such an outstanding library!

#### What version of SQLBoiler are you using (`sqlboiler --version`)?
SQLBoiler v2.1.7

This is a list of dependencies that are downloaded when I try to vendor imports from generated code: 
```
$ gb vendor fetch github.com/vattle/sqlboiler
fetching recursive dependency github.com/go-sql-driver/mysql
fetching recursive dependency github.com/kat-co/vala
fetching recursive dependency github.com/nullbio/inflect
fetching recursive dependency github.com/pkg/errors
fetching recursive dependency github.com/satori/go.uuid
fetching recursive dependency github.com/spf13/cobra
fetching recursive dependency github.com/spf13/pflag
fetching recursive dependency github.com/spf13/viper
fetching recursive dependency github.com/fsnotify/fsnotify
fetching recursive dependency github.com/hashicorp/hcl
fetching recursive dependency github.com/magiconair/properties
fetching recursive dependency github.com/mitchellh/mapstructure
fetching recursive dependency github.com/pelletier/go-toml
fetching recursive dependency github.com/pelletier/go-buffruneio
fetching recursive dependency github.com/spf13/afero
fetching recursive dependency github.com/spf13/cast
fetching recursive dependency github.com/spf13/jwalterweatherman
fetching recursive dependency golang.org/x/sys/unix
fetching recursive dependency golang.org/x/text/transform
fetching recursive dependency golang.org/x/text/unicode/norm
fetching recursive dependency gopkg.in/nullbio/null.v6
fetching recursive dependency gopkg.in/yaml.v2
```

I just wanted to get some DB access code generated and suddenly I end up including all those libs... 

From the packages above I would probably need only: 
- gopkg.in/nullbio/null.v6
- github.com/pkg/errors

Possible solution: 
- keep the core library as separate package (boil / queries / strmangle) 
- the generated code can depend on it
- the sqlboiler CLI also depends on it and includes the rest like viper / toml / yaml. 

What do you think? 

Best,
Roman

**Comment by aarondl** [comment]
So, I agree that there should not be so many dependencies, but I also don't think that there is this many in truth. *Most* of the list here is coming from viper, it's sort of a dependency nightmare. Cobra's also a bit of a culprit. The generated tests depend on viper, but you don't need to generate them (see the --no-tests flag).

The code doesn't reference viper or cobra outside main and the generated tests. This is a fault of the vendoring tool that it's not picking this up correctly. It should not try to vendor packages in tests/main.
The core library is a separate package in the dev branch. But even before that change none of the generated code can reference package main because that's not possible in Go.

When I delete the tests from a generated model set, this is what I see using `govendor list -v` (though admittedly probably an old version):

```text
 e  github.com/davecgh/go-spew/spew    
    ├──  e  github.com/davecgh/go-spew/spew
    └──  e  github.com/vattle/sqlboiler/queries
 e  github.com/davecgh/go-spew/spew/testdata    
    └──  e  github.com/davecgh/go-spew/spew
 e  github.com/nullbio/inflect    
    └──  e  github.com/vattle/sqlboiler/strmangle
 e  github.com/pkg/errors    
    ├──  e  github.com/pkg/errors
    ├──  l  github.com/vattle/sqlboiler/models
    └──  e  github.com/vattle/sqlboiler/queries
 e  github.com/vattle/sqlboiler/boil    
    ├──  l  github.com/vattle/sqlboiler/models
    └──  e  github.com/vattle/sqlboiler/queries
 e  github.com/vattle/sqlboiler/queries    
    ├──  l  github.com/vattle/sqlboiler/models
    └──  e  github.com/vattle/sqlboiler/queries/qm
 e  github.com/vattle/sqlboiler/queries/qm    
    └──  l  github.com/vattle/sqlboiler/models
 e  github.com/vattle/sqlboiler/strmangle    
    ├──  l  github.com/vattle/sqlboiler/models
    └──  e  github.com/vattle/sqlboiler/queries
 e  gopkg.in/DATA-DOG/go-sqlmock.v1    
    └──  e  github.com/vattle/sqlboiler/queries
 e  gopkg.in/nullbio/null.v6    
    ├──  l  github.com/vattle/sqlboiler/models
    └──  e  github.com/vattle/sqlboiler/queries
 e  gopkg.in/nullbio/null.v6/convert    
    └──  e  gopkg.in/nullbio/null.v6
 l  github.com/vattle/sqlboiler/models
```

This set of things seems fairly reasonable, and is pretty close to what you had in mind for dependencies. I'm not sure how to move forward from here, maybe I'll let you take a look closer at how you're using govendor, and maybe try deleting the tests from the generated code as that's a fairly important step to rid yourself of many dependencies.

**Comment by aarondl** [comment]
Stale.
