### ISSUE TITLE
DB Config through Environment Variable

### ISSUE THREAD

**Issue by fandybee** [vattle/sqlboiler#109]
Hi..

Thanks for the great project. I just want to ask how do we use environment variable for the db config?

**Comment by aarondl** [comment]
Everything can be sent in as environment variables.

Here's a snippet from main which shows the format:

```go
	viper.SetDefault("postgres.sslmode", "require")
	viper.SetDefault("postgres.port", "5432")
	viper.SetDefault("mysql.sslmode", "true")
	viper.SetDefault("mysql.port", "3306")
```

Please re-open if it doesn't work for you.

**Comment by fandybee** [comment]
Hi aaron..

i apologize i dont really understand, 
First the snippet you showed me are only for sslmode and port? what about host, username etc?
```
			User:    viper.GetString("postgres.user"),
			Pass:    viper.GetString("postgres.pass"),
			Host:    viper.GetString("postgres.host"),
			Port:    viper.GetInt("postgres.port"),
			DBName:  viper.GetString("postgres.dbname"),
                        SSLMode: viper.GetString("postgres.sslmode"),
```

Second im not too sure how to set the environment variable with a dot? or is there anyway specific way i should set up my Environment variable? i dont think dot is supported

**Comment by aarondl** [comment]
It was just an example, I didn't have the rest readily available. The rest follow the exact same pattern. Dot is not strictly supported nor strictly unsupported in environment: http://stackoverflow.com/questions/2821043/allowed-characters-in-linux-environment-variable-names

It worked when I tried it last time. The dot is an unfortunate thing we inherit from Viper with nested keys so it's fidgety to change.

Finally I'd caution you not to put your DB parameters in environment, but use a configuration file instead. The environment leaks secrets very easily by any process with any permission so you should not use them unless security is of no concern.

Read some of these to see why you shouldn't put your DB information in there and should use the config file instead:
http://movingfast.io/articles/environment-variables-considered-harmful/
https://github.com/docker/docker/issues/13490

Also remember that the secrets are not needed at runtime, only generation time. Past that, it's up to your app to create the sql.DB that you're going to work with so production constraints like "environment only" are not applicable here.

**Comment by fandybee** [comment]
Hi Aaron

First thanks for the response, Yes but the config is needed to run the models test suites, unless there is away for me in the code in the db config.
First Is there any best practice advice to do this on CI, since i have afew different environments for CI which will run the test suites.

**Comment by aarondl** [comment]
So, the advice I'd give you is not to run the generated tests in CI. Because that implies you're generating your models in CI. You should be generating your models on your development machine. And CI should just be using those to check the rest of your code.

Generation time is when you care about the generated tests. I'd suggest make a make/rakefile or whatever you prefer to do something like:
```bash
make regen-models
```

And have that generate models, run the tests, then clean the tests out on a successful pass. Then you commit everything except the tests.
That's to say, when you're doing development and changes on your database is when you'll be running the tests, not when CI is taking care of business.

Worst case scenario, just have your CI scripts dump the environment variables to the config file. Toml is painless to generate via echo statements.
Does this help?

**Comment by aarondl** [comment]
It's funny because I actually had changed this in v3 to make things worked like I wanted. This is a breaking change if just suddenly change the environment variables that exist, so I'll leave it fixed in v3 and simply unfortunate in v2 :(
