### ISSUE TITLE
MariaDB mysql client throws error: unknown variable 'ssl-mode=DISABLED'

### ISSUE THREAD

**Issue by doncasper** [vattle/sqlboiler#117]
**Version:** `SQLBoiler v2.2.0`
**Driver:** `github.com/go-sql-driver/mysql`

**I try to run tests for generated models:**
```
go test -v ./models/
```

**But I get error:**
```bash
failed running: mysql [--defaults-file=/tmp/optionfile136854353]

mysql: unknown variable 'ssl-mode=DISABLED'

Unable to execute setup: exit status 7
exit status 252
FAIL	sqlboiler_app/models	0.008s
```

My `sqlboiler.yaml`:
```yaml
mysql:
  dbname: mydb
  user: myuser
  pass: mypass
  host: 0.0.0.0
  port: 3306
  sslmode: false
```

Generated: `/tmp/optionfile136854353`:
```
[client]
host=0.0.0.0
port=3306
user=myuser
password=mypass
ssl-mode=DISABLED
[mysqldump]
host=0.0.0.0
port=3306
user=myuser
password=mypass
ssl-mode=DISABLED
```

**Comment by aarondl** [comment]
Hm. This is pretty strange given the documentation: https://dev.mysql.com/doc/refman/5.7/en/secure-connection-options.html#option_general_ssl-mode
What version of mysql & mysql client are you running? Maybe your version of mysql has been compiled (somehow) without ssl options? Or maybe it's mariadb and it has some different config for it or something?
Let me know what you've got for mysql versions and we'll go from there.

**Comment by doncasper** [comment]
Yes, I use `mysql  Ver 15.1 Distrib 10.0.29-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

I can create records and make a selection from the database, so I do not understand why the tests do not pass.

**Comment by aarondl** [comment]
So, I've looked into this and I've found the issue. For some reason the mysql client that ships with mariadb doesn't understand the `ssl-mode` option. This is true of versions 10.0, 10.1, and 10.2 from my testing. This is sort of an upstream bug with mariadb, if I were you I would file an issue against mariadb.
Unfortunately due to debian packaging there's no simple solution involving package managers to trade out the binary. But you could get the mysql binary and use that instead of the mariadb one, assuming they work the same.

There's also the obvious solution that we should downgrade to the deprecated ssl options to maintain compatibility but I'll push back on that and say that mariadb should up their game first. If we change this now, MySQL 8.0 will break for us. If we don't change it, MariaDB doesn't work. Rock and a hard place :(

**Comment by JordanShurmer** [comment]
FWIW there seems to be a workaround for the `--ssl-mode=DISABLED` case:

```
--skip-ssl
```

**Comment by mfechner** [comment]
I hit exactly the same problem, but could solve it by having in sqlboiler.toml:
```toml
[mysql]
  ...
  sslmode = "PREFERRED"
```
