### ISSUE TITLE
Mysql Decimal Data Type Support

### ISSUE THREAD

**Issue by cyrainfish** [vattle/sqlboiler#121]
It's really useful for me to generate ORM from Mysql, but I just find "Decimal Data Type" is regarded as string/null.String. Is there any special reason for this?  If no, I'm hoping to convert it to float64/null.Float64 like below:
-               case "double", "double precision", "real":
+               case "double", "double precision", "real", "decimal":

File : github.com/vattle/sqlboiler/bdb/drivers/mysql.go

Thanks!
Yu

**Comment by nullbio** [comment]
This was done because float64 can have precision errors when dealing with decimal values, which is particularly dangerous for financial code. You will need to do the conversions yourself for this, as there is no adequate storage in the stdlib large enough to safely represent the decimal values yet, as far as I am aware.

Here were some declined proposals: 

https://github.com/golang/go/issues/12332
https://github.com/golang/go/issues/12127

Here are some libraries that seem to be popular for conversions:

https://github.com/shopspring/decimal
https://github.com/ericlagergren/decimal

If precision is not important to you then you can just use strconv.ParseFloat().

**Comment by aarondl** [comment]
Keep in mind that we've talked about a custom driver that would allow you to select your own data types here: https://github.com/vattle/sqlboiler/pull/102
We'll get to it but eventually but it's not on any immediate roadmaps as we're busy on other things atm.
