### ISSUE TITLE
How to add support for other database (eg. Oracle)?

### ISSUE THREAD

**Issue by AP-Nothize** [vattle/sqlboiler#167]
What is the estimated effort and where should I begin?

**Comment by aarondl** [comment]
Hey there @AP-Nothize.

I'd invite you to check out the existing PRs which have previously added other DB support:
https://github.com/vattle/sqlboiler/pull/138 (waiting on #143 to merge)
https://github.com/vattle/sqlboiler/pull/119

Mainly it begins with creating a driver in bdb/drivers/x.go and ensuring that the `[]Tables` output is correct. You can see this by running `sqlboiler` with `--debug`. Please keep in mind we are attempting to refactor the way drivers work so that people don't need to compile all drivers since the most common scenario is to only use one, as well as facilitate forking to enable custom types (#143).

It will be blocked on merging until 143 lands, and although that's the main focus whenever I get sqlboiler time right now, time is short currently. Though there should be a ramp-up happening towards v3 in the coming months.
