### ISSUE TITLE
JSON/JSONB Support

### ISSUE THREAD

**Issue by psykomo** [vattle/sqlboiler#29]
Do you support Postgre's JSON/JSONB data type?

**Comment by aarondl** [comment]
Hey there @psykomo. We've identified one issue with working with JSON/B where the compatibility tests don't pass.

There's also some awkwardness since we treat JSON as a string. We're planning to add a new null.Bytes and null.JSON type to our null package so that we have much better support for this, and the null.JSON type will have marshal/unmarshal helpers just to make it nice.

Other than the types being correct, what else were you thinking in terms of support for this data type?

**Comment by mackross** [comment]
A typical use case would be to specify a custom type to be used as the unmarshal target.

**Comment by aarondl** [comment]
@mackross So, we have a new set of JSON types that are correct now in the dev branch.

In my current line of thinking your use case is not possible, at least not without some custom type abilities which we currently lack.

We now use proper JSON types in the dev branch, and support easy marshal/unmarshal operations via helpers:
https://github.com/vattle/sqlboiler/blob/a86e794b617b1e5566ae9394b62c404107b378a0/boil/types/json.go#L20

This looks like as much functionality we'll get for the meantime until we hear enough asks for a custom type system.

**Comment by nullbio** [comment]
Hi @mackross and @psykomo -- we've released V2 which includes the JSON types you've requested. See here for release notes: https://github.com/vattle/sqlboiler/releases/tag/v2.0.0

Thanks.
