### ISSUE TITLE
Add configuration opton to white-list tables

### ISSUE THREAD

**Issue by ajankovic** [vattle/sqlboiler#30]
It would be nice to have "include" option in configuration that would allow us to specify just the tables that we want to be processed by the generator, as opposite to "exclude".

**Comment by nullbio** [comment]
Can you please describe your use case for this? We actually had this feature at one point but decided to replace it with the blacklist functionality, because our assumption is that it should be a rare scenario for someone to only want to generate support for a few of their database tables (because the whole ORM and database generally acts as a cohesive unit; especially in regard to relationships), but a common scenario to exclude a few tables (like migration tables). Of course, if this assumption is wrong, we're open to the idea.

**Comment by ajankovic** [comment]
Sure.

it's problematic to blacklist if you have partitioned tables with table inheritance. So for example you have partitioned tables by month and you have master table which should actually be used for any interaction with that model. With current implementation each of those partitioned tables would have to be excluded individually which is cumbersome especially in development phase where these tables are generated automatically and different environments have different tables.

Also it's useful if you want to logically divide models into two or more packages to separate concerns. With whitelisting you could generate models for a subset of tables (e.g. blog, ecommerce, etc.).

If you don't think these are valid arguments for you to invest time I can probably create a pull request if your policy is to accept them.

**Comment by nullbio** [comment]
Fair enough. I have no problem with it, if @aarondl has no objections we can add this back in some time this week. Thanks.

**Comment by nullbio** [comment]
@ajankovic the feature is in the dev branch now, if you'd like to test it. We're going to work on the other features in the issues list before releasing them together.
