### ISSUE TITLE
problem when table has FK to itself

### ISSUE THREAD

**Issue by ryanbarry** [vattle/sqlboiler#39]
i've got the following table (postgres):
```sql
create table if not exists posts (
       id serial primary key not null,
       uuid uuid not null default (uuid_generate_v4()) unique,
       created_at_utc timestamp without time zone not null default (now() at time zone 'utc'),
       approved boolean not null default false,
       flagged boolean not null default false,
       -- problem here:
       parent_uuid uuid references posts (uuid),
       --
       updated_at_utc timestamp without time zone default null
);
```

but the generated code gives the following errors when building:
```
models/posts.go:330: cannot call non-function p.ParentUUID (type null.String)
models/posts.go:334: type Post has both field and method named ParentUUID
```

am i doing something wrong? is there a way to name things that won't cause this problem? Thanks in advance! Other than this minor issue, I'm really enjoying using this!

**Comment by aarondl** [comment]
Hi there @ryanbarry 

The problem here is that we treat `_id` suffixes specially. When we generate a foreign key "lookup" helper, we typically take the foreign key name and drop `_id` off of it. It's a convention noted in the 
[pro tips](https://github.com/vattle/sqlboiler#pro-tips) section of the readme. However I guess it sort of becomes a requirement when the foreign key is on the same table :(

We could consider `_uuid` to the list of things that we drop, but then maybe someone else will come along with another prefix. Anyway, changing your column name to `_id` _should_ fix the issue. And we'll see what we do about this in the long term.

Thanks for using sqlboiler!

**Comment by nullbio** [comment]
Hi @ryanbarry, is there a particular reason you are not using your unique uuid as your primary key, opposed to the serial id, or vice versa?

**Comment by nullbio** [comment]
@ryanbarry we've added uuid to the trim suffixes in the dev branch. Once these are merged into master (hopefully today) then you should not need to change any code, as long as you update your sqlboiler and regenerate.

**Comment by ryanbarry** [comment]
this is awesome, i really appreciate the quick turnaround! reason for having serial id & unique uuid is to expose uuid as an external identifier while keeping the serial id as internal to our datastore, while keeping querying simple. thanks again 😃

**Comment by nullbio** [comment]
Hey @ryanbarry, 2.0.1 has been released which includes the fixes for the issues you were having. Thanks.
