### ISSUE TITLE
Boolean value "false" not being inserted when column has a default value

### ISSUE THREAD

**Issue by jseriff** [vattle/sqlboiler#70]
We have a table with a boolean column with its default set to true.  We then try to insert a model into that table with a false value in that column.  The query is generated without the column in the insert statement (it is in the returning statement instead), causing the database to use its default value.

**Comment by aarondl** [comment]
This behavior is intentional. On insertion the mechanism is that:
For any field with a default value and a zero value in the Go struct, then it's assumed the user didn't set it and it should assume the default value so it's omitted from the query.

The only way to force it to do the right thing is wherever you're inserting this struct, simply list the columns you want to insert in the whitelist. The whitelist overrides this default mechanism and forces that column to appear in the query.

We used to have some nasty code that would parse the default value from postgres, try to coerce that into a default value, and check if it was equal to the default value before omitting it. But it was error prone and scary, full of regexes etc so I'd prefer not to bring it back.

Is this an acceptable solution?

**Comment by jseriff** [comment]
@aarondl I definitely agree that trying to parse out the default value from postgres is a bad path to head down, and I understand trying to use the database default values if the Go value appears to be "falsey".  

It definitely feels like weird behavior here however.  My preference is to avoid whitelists in most cases, so that i dont have to worry about missing them as I add columns - I tend to only use them when I am restricting the column list for a security reason.

Unfortunately, I dont have any great solutions off the top of my head for how to satisfy both of these use cases since there is no way to specify false vs. not set without using a null.Boolean, which also seems like the wrong approach.  In the very particular case where I am running into this, we can fairly easily switch to a whitelist approach (it is in a series of unit tests).  We will have to be on the lookout for it in the future however, as its not readily apparent that it was not setting this value.
