### ISSUE TITLE
Any plan to support cockroachdb?

### ISSUE THREAD

**Issue by iven1990** [vattle/sqlboiler#71]
Any plan to support cockroachdb?

**Comment by aarondl** [comment]
Hey there,

I'll point you to the issue you created and our responses here: https://github.com/vattle/sqlboiler/issues/68

The summary is: We don't have any plans because there's no motivation for us to support it. Having said that it's not difficult to add support for it.
You can look at the postgres driver here: https://github.com/vattle/sqlboiler/blob/master/bdb/drivers/postgres.go
It needs to conform to the driver.Interface here: https://godoc.org/github.com/vattle/sqlboiler/bdb#Interface

Thanks for your interest :)
