### ISSUE TITLE
SQL compatibility to MySQL 5

### ISSUE THREAD

**Issue by yangyuqian** [vattle/sqlboiler#76]
Hi,

I'm evaluating on the sqlboiler project, and it's really inspiring to me.

I found sqlboiler generates SQLs not working on MySQL 5, which is still the main database server in the company I serve.

i.e. 

```
-- SQL generated by sqlboiler, not working on MySQL 5
DELETE FROM mytable as t1 WHERE ...

-- compatible SQL would be
DELETE t1 FROM mytable as t1 WHERE ...
```

**Comment by aarondl** [comment]
See the quote from this page: https://www.mysql.com/support/eol-notice.html

> January 9, 2012
> 
> MySQL 5.0 covered under Oracle Lifetime Sustaining Support
> Per Oracle's Lifetime Support policy, MySQL 5.0 is now covered under Oracle Sustaining Support.
> 
> Users are encouraged to upgrade to MySQL 5.5.
>
> December 31, 2009
> 
> MySQL 5.0 Active Support ended on December 31, 2009 - Now in Extended Support Phase
> Per the MySQL Support Lifecycle policy, active support for MySQL 5.0 ended on December 31, 2009. MySQL 5.0 is now in the Extended support phase.

Unfortunately MySQL 5.0 has been dead for a long time, I highly encourage you to upgrade your version of MySQL if it's still in production use at your company. There have been a LOT of security fixes in this time, and there are probably known security vulnerabilities for this version. This is actually fairly dangerous to continue to run this version of MySQL.

Now that I've said that, let's talk about the issue. The syntax you're saying is "compatible" is a syntax that's still valid today in MySQL 5.7, it's called multi-table delete. This is the same as it was in MySQL 5.0 from what this documentation suggests: http://downloads.mysql.com/docs/refman-5.0-en.a4.pdf

The SQLBoiler generated SQL statement should work looking at this documentation. Can you show the error message you're receiving or provide any more information, since what you're claiming according to the documentation doesn't appear to be true.

**Comment by yangyuqian** [comment]
Hi, 

Sorry for the confusing question.

I'm working with MySQL 5.5, and it simply throws "Syntax error ..."

A work around is modify "buildDeleteQuery":

```
  113 func buildDeleteQuery(q *Query) (*bytes.Buffer, []interface{}) {
  114     var args []interface{}
  115     buf := strmangle.GetBuffer()
  116
! 117     buf.WriteString("DELETE `a` FROM ")
  118     buf.WriteString(strings.Join(strmangle.IdentQuoteSlice(q.dialect.LQ, q.dialect.RQ, q.from), ", "))
```

and the sql will be

```
DELETE a FROM t1 as a ...
```

Do you think this is the correct way to fix this issue? I'll be happy to submit PRs on MySQL.

**Comment by aarondl** [comment]
Can you turn on debugging mode and show the full query? From what you're telling me it doesn't look like a syntax error for MySQL 5.5 since even 5.0 doesn't have a problem with this syntax.
Instructions are here: https://github.com/vattle/sqlboiler#diagnosing-problems
> For errors with other causes, it may be simple to debug yourself by looking at the generated code. Setting boil.DebugMode to true can help with this. You can change the output using boil.DebugWriter (defaults to os.Stdout).

**Comment by yangyuqian** [comment]
Hi,

Below are some screenshots to run the delete queries against MySQL 5.5.44

The Table:
![image](https://cloud.githubusercontent.com/assets/7478577/21210863/a539e3ce-c2b9-11e6-8b14-7046fbabd494.png)

The Query:
![image](https://cloud.githubusercontent.com/assets/7478577/21210886/cd66ca88-c2b9-11e6-9cbd-47fb55d5d4ba.png)

After I update the query from "DELETE FROM ..." to "DELETE a FROM ...",  it works 
![image](https://cloud.githubusercontent.com/assets/7478577/21210920/f59bb0ea-c2b9-11e6-92ef-485df4c664e8.png)

**Comment by aarondl** [comment]
Your problem is you're mixing syntax. The syntax you're showing that's "broken" is called a multi-table delete
that has incorrect syntax in it.

### Multi-Table deletion syntax

Correct syntax is below. But keep in mind that there is NO reason to do this for a single table, please see the Single-Table deletion syntax below.

```sql
mysql> DELETE a FROM apps as a where id = 50;
Query OK, 0 rows affected (0.00 sec)
```

Mistaken syntax:

```sql
mysql> DELETE FROM apps AS a WHERE id = 50;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS a WHERE id = 50' at line 1
```

### Single-Table deletion syntax
To delete records from a single table, you simply do not use the "as" statement.

```sql
mysql> DELETE FROM apps WHERE id = 50;
Query OK, 0 rows affected (0.00 sec)
```

This is not an incompatibility with MySQL and is indeed standards compliant with the [SQL Standard](http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt) as well:
```text
<delete statement: searched> ::=
  DELETE FROM <table name>
    [ WHERE <search condition> ]
```

I don't believe this is a version problem, as MySQL has had this since 5.0. I highly recommend you try to use the **Single-Table Deletion Syntax** and remove the "AS" keyword
completely. Then this will work without any problems.

**Comment by yangyuqian** [comment]
Sound good, and yes, it works to avoid Multi-Table deletion~

Thank you!
