### ISSUE TITLE
Generated code does not compile if table has column named "properties"

### ISSUE THREAD

**Issue by hannson** [vattle/sqlboiler#86]
Compilation fails with:
```

./picture.go:380: cannot call non-function o.Properties (type null.String)
./picture.go:384: type Picture has both field and method named Properties
```

```
// Picture is an object representing the database table.
type Picture struct {
	ID         int64       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Created    time.Time   `boil:"created" json:"created" toml:"created" yaml:"created"`
	Properties null.String `boil:"properties" json:"properties,omitempty" toml:"properties" yaml:"properties,omitempty"`
	Updated    time.Time   `boil:"updated" json:"updated" toml:"updated" yaml:"updated"`
	UserID     null.Int64  `boil:"user_id" json:"user_id,omitempty" toml:"user_id" yaml:"user_id,omitempty"`
	PicIndex   null.Int    `boil:"pic_index" json:"pic_index,omitempty" toml:"pic_index" yaml:"pic_index,omitempty"`
	URL        null.String `boil:"url" json:"url,omitempty" toml:"url" yaml:"url,omitempty"`

	R *pictureR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L pictureL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}


// Properties retrieves all the property's property with an executor.
func (o *Picture) Properties(exec boil.Executor, mods ...qm.QueryMod) propertyQuery {
	queryMods := []qm.QueryMod{
		qm.Select("`a`.*"),
	}

	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.InnerJoin("`property_pictures` as `b` on `a`.`id` = `b`.`property_id`"),
		qm.Where("`b`.`pictures_id`=?", o.ID),
	)

	query := Properties(exec, queryMods...)
	queries.SetFrom(query.Query, "`property` as `a`")
    	return query
}
```

**Comment by aarondl** [comment]
So the reason for this isn't only that there's a column named properties, but it appears that there's a table named Property too. As you can see the `Properties` method's job is to look up the Properties of the Picture.

It's doing this query:
```sql
select property.*
from property
inner join property_pictures on property.id = property_pictures.property_id
where property_pictures.pictures_id = ?
```

So it looks like property_pictures has fkeys to picture and property which is creating a many-to-many relationship.

SQLBoiler has no fine-tuned controls (yet) for setting which names get converted how, or which relationships get generated. So currently the only suggestion I could make is that you change the column name `Properties` so as not to conflict with the relationship helper `Properties` which is being generated for you. It's a tad confusing too, since your properties are stored on a different table. Is this a caching column to avoid joining for property lookups? Is it a different kind of property? Is it more aptly named metadata? I'm not sure these are just a few questions trying to get to the bottom of why the schema is the way it is.

Of course I'm not trying to push the issue away from SQLBoiler. We might envision a complex mechanism to be able to map names or prevent certain names from being used and generate the relationship helper as "Properties2" or something (doesn't have the same ring does it)? but first let's talk about this schema.

**Comment by hannson** [comment]
It's a different type of property. The property table contains the Property(s) of a property management system. The properties column is inherited from some AbstractUserOwnedBaseCrudEntity (isn't the Java world wonderful) and stores a JSON object containing arbitrary class members or something. I'm going to see if I can safely drop the column in the Java version and then move forward with the Go port. 

In any case I think it should be renamed to avoid confusion anyway.

**Comment by aarondl** [comment]
Okay. For the meantime I'll consider this closed. If hard pressed we may bend and change this to do incremental naming with numbers, but I want to continue to try to get people to make sane databases that result in sane naming first. Thanks very much for your patience and willingness to change on your side so we can keep this project simple. I don't think anybody truly wants to see `picture.Properties2()` in their code  lol.
