### ISSUE TITLE
Error when running tests

### ISSUE THREAD

**Issue by gshilin** [vattle/sqlboiler#90]
Version: `v2.1.5 dev`

Running `go test` :

```go
# .../kmodels/boil_queries.go:25: cannot use q (type *".../mdb/vendor/github.com/vattle/sqlboiler/queries".Query) as type *"github.com/vattle/sqlboiler/queries".Query in argument to qm.Apply
```

**Comment by aarondl** [comment]
This is obviously a vendoring problem. What happens when you vendor is the types that are vendored become a "different type" than the regular package contains. You have to make sure your sqlboiler models folder (and therefore the tests) is also using the vendored `github.com/vattle/sqlboiler/queries` package. This should automatically happen so long as your folder structure looks like this:
```
$GOPATH
|-- src
|---- github.com
|------ gshilin
|-------- project
|---------- models (the models package must be at the same level as vendor, or deeper in folder structure, it can -not- be outside "project" above)
|---------- vendor (where your sqlboiler packages are vendored)
```

You elided some of the above output so I can't see exactly, all I know is that where you elided (ie. where it's sensitive) seems to be different. In this set up your `kmodels` folder should be inside the `mdb` folder (or a subfolder of mdb) since that's where your vendoring starts affecting packages adjacent and below it in the directory tree.

If you can't fix this and you think that it's still an sqlboiler problem, please post your folder structure here. I just want to see which folders are nested where in relation to `$GOPATH`).

**Comment by gshilin** [comment]
$GOPATH/src/github.com/gshilin/mdb
├── kmodels
├── vendor
│   ├── github.com
│   │   └── vattle
│   │       └── sqlboiler
│   ├── golang.org
│   └── gopkg.in

**Comment by aarondl** [comment]
I'm afraid I'm having a hard time reproducing this one. I created a folder under $GOPATH/src called project. I put my model directory there, and copied sqlboiler into my vendor folder. Here's the tree output with the contents of sqlboiler omitted:

```text
└[~/g/s/project]> tree
.
├── main.go
├── models
│   ├── boil_main_test.go
│   ├── boil_queries.go
│   ├── boil_queries_test.go
│   ├── boil_suites_test.go
│   ├── boil_types.go
│   ├── main_test.go
│   ├── users.go
│   └── users_test.go
├── sqlboiler.toml
└── vendor
    └── github.com
        └── vattle
```

And when I actually go to test things:

```text
└[~/g/s/project]> go test ./...
?   	project	[no test files]
ok  	project/models	0.532s
ok  	project/vendor/github.com/vattle/sqlboiler	0.537s
ok  	project/vendor/github.com/vattle/sqlboiler/bdb	0.003s
?   	project/vendor/github.com/vattle/sqlboiler/bdb/drivers	[no test files]
ok  	project/vendor/github.com/vattle/sqlboiler/boil	0.007s
ok  	project/vendor/github.com/vattle/sqlboiler/queries	0.003s
?   	project/vendor/github.com/vattle/sqlboiler/queries/qm	[no test files]
ok  	project/vendor/github.com/vattle/sqlboiler/randomize	0.002s
ok  	project/vendor/github.com/vattle/sqlboiler/strmangle	0.003s
ok  	project/vendor/github.com/vattle/sqlboiler/types	0.002s
```

Everything seems to work fine?

**Comment by aarondl** [comment]
Stale.
