### ISSUE TITLE
Select query fired after insertion

### ISSUE THREAD

**Issue by yavuzyurtbegendi** [vattle/sqlboiler#99]
### What version of SQLBoiler are you using (`sqlboiler --version`)?
v5

After inserting a record, there is a select query called by sqlboiler, it is a performance issue for us, 

How can I solve this issue :) ? thanks

**Comment by aarondl** [comment]
Hey @yavuzyurtbegendi, this is intentional. I guess you're using MySQL. The reason we do this is to keep the struct in sync with the database for default values. If you have no default values and no auto incrementing ID then this shouldn't happen. If you don't want this behavior you can use raw queries to side-step it.
